### PR TITLE
Ubp 5.1 deb

### LINKED ISSUE #643: Enable installation of "deb" Nexus 7 2013 gsm
### Description of the feature
Enable installation of "deb" Nexus 7 2013 gsm 

There is no porting needed. Not even compiling images. All the pieces are on the image server already. I think the only thing missing is some glue in the json files on the server or maybe in the installer. 

The "deb" is the sibling of the "flo" device. The flo is the wifi version, deb is gsm. 

### Steps to reproduce
- use ubports-installer
- try to install for deb

### Expected behavior
Can be installed

### Actual behavior
deb is not an option in the installer 

### Workaround 
NB: some steps are written from memory, syntax might be slightly different 
- install flo images with the installer
- boot, look around, 
=> observe that basically everything works (except sound)
- manually download the deb device image from image server
  - http://system-image.ubports.com/pool/device-1b9d2f7256c3d6c98ba93b66ad48d9ce75833978cd65364df45693e0d40b27a1.tar.xz
  - NB: link is taken from here: 
system-image.ubports.com/ubports-touch/15.04/rc/deb/index.json look for 15.04, deb, rc, v3
  - `tar xf device-1b9*a1.tar.xz`
  - you need the `partitions/boot.img` and the `system/var/lib/lxc/android/system.img` for the following steps
- replace the /var/lib/lxc/android/system.img file on the device:
  - boot into recovery mode 
  - mount the system.img `cd data; mkdir mnt; mount system.img mnt ; `
  - `cd mnt/var/lib/lxc/android`
  - replace the system.img here with the one you just downloaded from the system-image server
- replace the boot.img
  - boot into fastboot mode 
  - `fastboot flash boot boot.img` 
- reboot into UT
=> observe that basically everything works including sound

### PR DESCRIPTION
**Pull request by doniks**
this should build for Nexus 7 deb
should fix https://github.com/ubports/ubuntu-touch/issues/643#issuecomment-468911051
making a draft PR to try this in jenkins

### CODE REVIEW

**Comment by doniks** [comment]
@Flohack74 as per our tg chat ... can you try this?

**Comment by Flohack74** [comment]
I will try, yes.

**Comment by doniks** [comment]
ugh, I don't understand this. how do I test this locally? am I supposed to `repo init -u https://github.com/ubports/android -b ubp-5.1 --depth=1`, or `-b ubp-5.1-allthefixings` the difference is a bunch of manifest entries that would overlap with the devices.xml in here ... is devices.xml even used? Now I can't even `../build.sh hammerhead-userdebug` anymore :( Thanks for you help so far @Flohack74 - speak to you later

**Comment by doniks** [comment]
ready to merge

we still need to get the defconfig update in too: https://github.com/doniks/android_kernel_google_msm/commit/7c4b9bc382756d2dcc3160260c0af182cc984959.patch

**Comment by Flohack74** [comment]
Is this the only commit that makes it different to our version? Then I will just check it out and commit this by hand.

**Comment by doniks** [comment]
> Is this the only commit that makes it different to our version? 

Yes

**Pull request merged**
